-- Especificação 
CREATE OR REPLACE PACKAGE PKG_PACOTE IS
    PROCEDURE CALCULA_REAJUSTE(P_VAL_ATUAL IN NUMBER);
END PKG_PACOTE;
/


-- Corpo
CREATE OR REPLACE PACKAGE BODY PKG_PACOTE IS 
    PROCEDURE CALCULA_REAJUSTE(P_VAL_ATUAL IN NUMBER) IS
        V_REAJUSTADO NUMBER(7,2);
    BEGIN
        V_REAJUSTADO := P_VAL_ATUAL * 1.25;
        DBMS_OUTPUT.PUT_LINE('SALÁRIO ATUAL: R$' || P_VAL_ATUAL);
        DBMS_OUTPUT.PUT_LINE('SALÁRIO REAJUSTADO: R$' || V_REAJUSTADO);
    END CALCULA_REAJUSTE;
END PKG_PACOTE;
/

SET SERVEROUTPUT ON;
EXECUTE PKG_PACOTE.calcula_reajuste(2000);