DROP TABLE PRODUTO_CP;

CREATE TABLE PRODUTO_CP(
    CODIGO NUMBER(4),
    CATEGORIA CHAR(1),
    VALOR NUMBER(4,2)
);

INSERT INTO PRODUTO_CP VALUES (1001, 'A', 7.55);
INSERT INTO PRODUTO_CP VALUES (1002, 'B', 5.95);
INSERT INTO PRODUTO_CP VALUES (1003, 'C', 3.45);


SET SERVEROUTPUT ON

DECLARE
    CURSOR C_PRODUTO IS SELECT*FROM PRODUTO_CP;
    V_PRODUTO C_PRODUTO%ROWTYPE;
BEGIN
    FOR I IN C_PRODUTO LOOP
        IF I.CATEGORIA = 'A' THEN
            I.VALOR := I.VALOR*1.05;
            UPDATE PRODUTO_CP SET VALOR = I.VALOR WHERE CODIGO = I.CODIGO;
            DBMS_OUTPUT.PUT_LINE('VALOR REAJUSTADO DO PRODUTO A: '||I.VALOR);
        ELSIF I.CATEGORIA = 'B' THEN
            I.VALOR := I.VALOR*1.1;
            UPDATE PRODUTO_CP SET VALOR = I.VALOR WHERE CODIGO = I.CODIGO;
            DBMS_OUTPUT.PUT_LINE('VALOR REAJUSTADO DO PRODUTO B: '||I.VALOR);
        ELSIF I.CATEGORIA = 'C' THEN
            I.VALOR := I.VALOR*1.15;
            UPDATE PRODUTO_CP SET VALOR = I.VALOR WHERE CODIGO = I.CODIGO;
            DBMS_OUTPUT.PUT_LINE('VALOR REAJUSTADO DO PRODUTO C: '||I.VALOR);
        END IF;
    END LOOP;
END;

SELECT*FROM PRODUTO_CP