DROP TABLE ALUNO CASCADE CONSTRAINTS;

CREATE TABLE ALUNO (
    RM NUMBER(1),
    NOME VARCHAR2(20)
);

INSERT INTO ALUNO VALUES(1,'João');
INSERT INTO ALUNO VALUES(2,'Maria');
INSERT INTO ALUNO VALUES(3,'José');
INSERT INTO ALUNO VALUES(3,'José');
COMMIT;


--- TRATANDO ERROS ESPECÍFICOS
SET SERVEROUTPUT ON

DECLARE
    V_RM ALUNO.RM%TYPE := 3;
    V_NOME ALUNO.NOME%TYPE;
BEGIN
    SELECT NOME INTO V_NOME FROM ALUNO WHERE RM=V_RM;
    DBMS_OUTPUT.PUT_LINE(V_RM ||' - '|| V_NOME);
EXCEPTION
     WHEN NO_DATA_FOUND THEN
     DBMS_OUTPUT.PUT_LINE ('Não há nenhum aluno com este RM');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE ('Há mais de um aluno com este RM');
END;


--- TRATANDO ERROS DE FORMA GERAL
SET SERVEROUTPUT ON

DECLARE
    V_RM ALUNO.RM%TYPE := 3;
    V_NOME ALUNO.NOME%TYPE;
BEGIN
    SELECT NOME INTO V_NOME FROM ALUNO WHERE RM=V_RM;
    DBMS_OUTPUT.PUT_LINE(V_RM ||' - '|| V_NOME);
EXCEPTION
     WHEN OTHERS THEN
     --Mostra o código do erro
     DBMS_OUTPUT.PUT_LINE (sqlcode);
     --Mostra a mensagem do erro
     DBMS_OUTPUT.PUT_LINE (sqlerrm);
END;