DROP TABLE FUNCIONARIO;

CREATE TABLE FUNCIONARIO(
    ID_FUNC NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR2(100),
    SALARIO NUMBER(10,2)
);


INSERT INTO FUNCIONARIO(NOME, SALARIO) VALUES ('Luiz', 1000);
INSERT INTO FUNCIONARIO(NOME, SALARIO) VALUES ('Clodoaldo', 1300);
INSERT INTO FUNCIONARIO(NOME, SALARIO) VALUES ('Monica', 3000);
INSERT INTO FUNCIONARIO(NOME, SALARIO) VALUES ('Jose', 2000);


----------------------------------------------


CREATE OR REPLACE 
PROCEDURE SP_RELATORIO_SALARIO AS 
    CURSOR C_FUNC IS 
    SELECT * FROM FUNCIONARIO;
    
BEGIN 
    FOR REG IN C_FUNC LOOP 
        IF REG.SALARIO > 1500 THEN
            DBMS_OUTPUT.PUT_LINE(REG.NOME||' '||REG.SALARIO);
        END IF;
    END LOOP;

END;
/

CREATE OR REPLACE 
PROCEDURE SP_INCLUI_FUNCIONARIO(P_NOME VARCHAR2, P_SALARIO NUMBER) IS

BEGIN
    INSERT INTO FUNCIONARIO(NOME, SALARIO) VALUES(P_NOME, P_SALARIO);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('FUNCIONÁRIO: '||P_NOME||' FOI INCLUÍDO COM SUCESSO!');

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERRO NA INCLUSÃO DO FUNCIONÁRIO: '||SQLERRM);
END;
/

CREATE OR REPLACE 
FUNCTION SF_MEDIA_NOTA(NOTA1 NUMBER, NOTA2 NUMBER, NOTA3 NUMBER)
RETURN NUMBER IS
V_MEDIA NUMBER(3,1);

BEGIN
    V_MEDIA := (NOTA1 + NOTA2 + NOTA3)/3;
    RETURN V_MEDIA;
     
END;
/


------------------------------------------


--FORMAS DE CHAMAR A PROCEDURE CRIADA
SET SERVEROUTPUT ON;
EXEC sp_relatorio_salario;


SET SERVEROUTPUT ON;
EXEC sp_inclui_funcionario('Neymar', 3000);


SET SERVEROUTPUT ON;
DECLARE
BEGIN
dbms_output.put_line('Média: '||sf_media_nota(7,6,8));
END;